import { TripPackage } from '../src/types';
import * as fs from 'fs';
import * as path from 'path';

// Existing 26 packages base
import { tripPackages as existing26 } from '../src/data/trips';

// 28 Confirmed New Domestic Packages
const confirmed28: TripPackage[] = [
  // ── 27. LADAKH: DELHI TO UMLING LA & HANLE 12D ──
  {
    id: 'ladakh-bike-delhi-hanle-umlingla-12d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Delhi to Umling La & Hanle Trans-Himalayan Bike Expedition',
    subtitle: 'Ride through Manali, Leh, Umling La (19,024 ft) & Dark Sky Reserve Hanle',
    shortDescription: 'The ultimate motorcycle expedition from Delhi crossing Manali, high Himalayan passes, Umling La world record road, and stargazing in Hanle before returning via Tso Moriri.',
    longDescription: 'A premier 12-day self-ride motorcycle journey across the Trans-Himalayas. Ride through Manali, cross Sarchu and Khardung La, reach the highest motorable road in the world at Umling La (19,024 ft), observe galaxies at Hanle Dark Sky Reserve, and camp by Tso Moriri.',
    durationNights: 11,
    durationDays: 12,
    pricePerPerson: 28999,
    originalPrice: 35999,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 88,
    category: 'Motorbike',
    badge: 'Umling La 19,024 ft',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=90&w=2600&auto=format&fit=crop',
      alt: 'Adventure motorcycle on a high-altitude Himalayan mountain pass in Ladakh',
      location: 'Umling La Pass, Ladakh',
    },
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=90&w=1600&auto=format&fit=crop', alt: 'Night sky and Milky Way at Hanle Dark Sky Reserve' },
      { src: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=90&w=1600&auto=format&fit=crop', alt: 'Cobalt blue waters of Tso Moriri lake' },
    ],
    route: 'Delhi → Manali → Jispa → Sarchu → Leh → Nubra → Pangong → Hanle → Umling La → Tso Moriri → Manali → Delhi',
    inclusions: [
      'Royal Enfield Himalayan 411cc / Classic 350 with Fuel',
      '11 Nights Hotel, Swiss Camp & Homestay Stays',
      'Daily Breakfast & Hearty Dinners',
      'Experienced Road Captain & Certified Royal Enfield Mechanic',
      'Luggage Backup Vehicle & First Aid with Oxygen Cylinders',
      'Inner Line Permits & Wildlife Fees Included',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Ladakh Bike Trip — Delhi → Manali → Leh → Hanle → Umling La → Tso Moriri → Delhi',
      sourceUrl: 'https://internationalyouthclub.org/tours/ladakh-bike-trip-delhi-manali-leh-hanle-umlingla',
      sourceCheckedAt: '2026-08-21',
      pricingVariantsNote: 'Solo rider: ₹35,999, Dual rider: ₹28,999, Seat in backup vehicle: ₹24,999',
    },
  },

  // ── 28. LADAKH: DELHI TO SRINAGAR TRAVERSE 12D ──
  {
    id: 'ladakh-bike-delhi-srinagar-12d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Delhi to Srinagar via Umling La & Hanle Motorcycle Traverse',
    subtitle: 'One-way cross-Himalayan traverse from Delhi to Srinagar valley',
    shortDescription: 'Traverse the entire Himalayan breadth from the plains of Delhi up to Umling La and Hanle, exiting through the historic Kargil war memorial and lush Sonamarg to Srinagar.',
    longDescription: 'An expansive point-to-point traverse across the western Himalayas. Ride through Himachal passes to Leh, ascend Umling La and Hanle, and descend along the dramatic Zojila pass into Kashmir.',
    durationNights: 11,
    durationDays: 12,
    pricePerPerson: 35999,
    originalPrice: 42999,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 74,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=90&w=2600&auto=format&fit=crop',
      alt: 'Riders on high mountain highway between Leh and Kargil',
      location: 'Kargil Highway, Ladakh',
    },
    route: 'Delhi → Manali → Leh → Nubra → Pangong → Hanle → Umling La → Kargil → Drass → Srinagar',
    inclusions: [
      'Expedition Motorcycle & Comprehensive Fuel Support',
      '11 Nights Accommodation in Premium Camps & Heritage Houseboats',
      'Breakfast and Dinner Daily',
      'Support Vehicle, Road Captain & Mechanic Team',
      'Kashmir & Ladakh ILP Inner Line Permits',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Ladakh Bike Trip — Delhi → Leh → Hanle → Umling La → Srinagar',
      sourceUrl: 'https://internationalyouthclub.org/tours/ladakh-bike-trip-delhi-leh-hanle-srinagar',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 29. LADAKH: SRINAGAR TO DELHI 12D ──
  {
    id: 'ladakh-bike-srinagar-delhi-12d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Srinagar to Manali & Leh Trans-Himalayan Motorcycle Circuit',
    subtitle: 'Gradual altitude ascent starting in Kashmir, crossing Ladakh to Manali',
    shortDescription: 'Begin riding through the cedar glades of Kashmir, acclimatize through Kargil and Leh, explore Nubra and Pangong, and finish across Rohtang Pass to Delhi.',
    longDescription: 'The classic gentle acclimatization route. Start beside Dal Lake in Srinagar, ride up Zojila Pass into Ladakh, marvel at Pangong Tso, and cross Sarchu into Himachal.',
    durationNights: 11,
    durationDays: 12,
    pricePerPerson: 32000,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 62,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=90&w=2600&auto=format&fit=crop',
      alt: 'Mountain highway winding through barren brown peaks of Ladakh',
      location: 'Zojila Pass to Leh Highway',
    },
    route: 'Srinagar → Sonamarg → Kargil → Leh → Nubra → Pangong → Sarchu → Jispa → Manali → Delhi',
    inclusions: [
      'Royal Enfield Himalayan Motorcycle & Fuel',
      '11 Nights Hotel & Tent Stays',
      'Breakfast & Dinner Daily',
      'Road Captain & Luggage Backup Truck',
      'Inner Line Permits and Border Sanctions',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Ladakh Bike Trip — Srinagar → Leh → Manali → Delhi',
      sourceUrl: 'https://internationalyouthclub.org/tours/ladakh-bike-trip-srinagar-leh-manali',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 30. LADAKH: HANLE & DEMCHOK 7D ──
  {
    id: 'ladakh-bike-hanle-demchok-7d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Hanle, Umling La & Demchok Border Motorcycle Circuit',
    subtitle: '7-day focused high-pass ride to the Indo-China border sector and Hanle',
    shortDescription: 'A focused Eastern Ladakh circuit visiting Hanle Dark Sky Sanctuary, Umling La Pass at 19,024 ft, and the remote border village of Demchok.',
    longDescription: 'Ride from Leh through Chumathang hot springs to Hanle, ascend Umling La, and visit the historic border hamlet of Demchok along the Indus river.',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 24500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 45,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=90&w=2600&auto=format&fit=crop',
      alt: 'Stargazing at Hanle astronomical observatory',
      location: 'Hanle, Ladakh',
    },
    route: 'Leh → Chumathang → Hanle → Umling La → Demchok → Nyoma → Leh',
    inclusions: [
      'Motorcycle & Fuel from Leh',
      '6 Nights Homestays and Camps',
      'Meals as per Itinerary',
      'Border Permits for Demchok & Hanle',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Ladakh Bike Trip — Leh → Hanle → Umling La → Demchok → Leh (6N/7D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/ladakh-bike-trip-hanle-umlingla-demchok-6d',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 31. LADAKH: HANLE & DEMCHOK 8D ──
  {
    id: 'ladakh-bike-hanle-demchok-8d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Complete Eastern Ladakh, Nubra & Demchok Motorcycle Expedition',
    subtitle: '8-day circuit covering Nubra sand dunes, Pangong lake, Hanle & Demchok',
    shortDescription: 'The comprehensive 8-day ride covering Nubra Valley, Pangong Tso, Hanle Dark Sky Reserve, and the highest motorable road at Umling La.',
    longDescription: 'Combine iconic Ladakh highlights with extreme remote border valleys. Cross Khardung La, ride the Shayok river road to Pangong, and push east to Hanle and Demchok.',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 27999,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 53,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=90&w=2600&auto=format&fit=crop',
      alt: 'Pangong lake shoreline with rider in distance',
      location: 'Pangong Tso, Ladakh',
    },
    route: 'Leh → Nubra → Pangong → Hanle → Umling La → Demchok → Leh',
    inclusions: [
      'Motorcycle with Fuel & Maintenance',
      '7 Nights Stays in Camps and Hotels',
      'Daily Meals',
      'Inner Line Permits and Border Passes',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Ladakh Bike Trip — Leh → Hanle → Umling La → Demchok → Leh (7N/8D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/ladakh-bike-trip-hanle-umlingla-demchok-8d',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 32. LADAKH: CHADAR TREK 2026 ──
  {
    id: 'ladakh-chadar-trek',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Chadar Frozen Zanskar River Winter Expedition',
    subtitle: 'Walk on the frozen Zanskar river gorge in sub-zero winter temperatures',
    shortDescription: 'The world-famous frozen river trek over the Zanskar ice sheet, passing crystalline frozen waterfalls and sheer canyon walls.',
    longDescription: 'An iconic Himalayan winter expedition. Walk on the thick sheet of glass ice formed over the flowing Zanskar river in January and February, camp in winter caves, and witness Naerak waterfall frozen in time.',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 18500,
    originalPrice: 21000,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 112,
    category: 'Trekking',
    badge: 'Winter Ice Trek',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?q=90&w=2600&auto=format&fit=crop',
      alt: 'Trekker walking on frozen river sheet in snow canyon',
      location: 'Zanskar River, Ladakh',
    },
    route: 'Leh → Shingra Koma → Tibb Cave → Naerak Waterfall → Leh',
    inclusions: [
      '7 Nights in Leh Guesthouses & Heavy-Duty Winter Alpine Tents',
      'All Meals on Trek Prepared by Expedition Cook',
      'Local Zanskari Guides, Porters & Safety Gear',
      'Oxygen Cylinders and First Aid Support',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Chadar Trek 2026 (Frozen Zanskar River Expedition)',
      sourceUrl: 'https://internationalyouthclub.org/treks/chadar-trek-2026',
      sourceCheckedAt: '2026-08-21',
      pricingVariantsNote: 'Excludes mandatory Leh ALTOA medical checkup and local wildlife fee.',
    },
  },

  // ── 33. LADAKH: SHORT GLIMPSE 4D ──
  {
    id: 'ladakh-short-glimpse-4d',
    destinationId: 'ladakh',
    destination: 'Ladakh',
    title: 'Leh High-Altitude Weekend Glimpse',
    subtitle: 'Short 4-day introduction to Leh monasteries and Khardung La pass',
    shortDescription: 'A compact high-altitude long weekend exploring Sham valley, Indus-Zanskar confluence, and Khardung La pass.',
    longDescription: 'Designed for travellers with limited time. Acclimatize in Leh, visit Magnetic Hill and Sangam, and ascend to Khardung La viewpoint.',
    durationNights: 3,
    durationDays: 4,
    pricePerPerson: 13250,
    isPriceOnRequest: false,
    rating: 4.7,
    reviewCount: 38,
    category: 'Weekend',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=90&w=2600&auto=format&fit=crop',
      alt: 'Monastery overlooking Leh valley',
      location: 'Leh Palace, Ladakh',
    },
    route: 'Leh → Sham Valley → Khardung La → Leh',
    inclusions: [
      '3 Nights Hotel in Leh with Heating',
      'Daily Breakfast and Dinner',
      'Private Vehicle for All Sightseeing',
      'Airport Transfers and Permits',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Leh Ladakh Short Glimpse (4D/3N)',
      sourceUrl: 'https://internationalyouthclub.org/tours/leh-ladakh-4d',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 34. SPITI: WINTER 4X4 EXPEDITION 8D ──
  {
    id: 'spiti-winter-white-expedition',
    destinationId: 'spiti',
    destination: 'Spiti Valley',
    title: 'Winter Spiti 4x4 White Expedition',
    subtitle: 'Drive into snowbound Spiti valley with 4x4 vehicles and warm homestays',
    shortDescription: 'Experience the extreme stillness of white Spiti in winter, visiting snow-covered Key monastery, frozen Chicham bridge, and quiet Himalayan villages.',
    longDescription: 'When deep snow closes the high passes, enter Spiti through the Kinnaur valley in sturdy 4x4 vehicles. Stay in traditional mud homestays heated by wood-fired bukharis, and witness frozen waterfalls.',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 22500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 56,
    category: 'Adventure',
    badge: 'Winter White Spiti',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=90&w=2600&auto=format&fit=crop',
      alt: 'Snow-covered mountain road in winter Spiti',
      location: 'Chicham, Spiti Valley',
    },
    route: 'Shimla → Kalpa → Kaza → Key → Hikkim → Chicham → Shimla',
    inclusions: [
      '4x4 SUV Vehicle with Experienced Winter Driver',
      '7 Nights in Heated Homestays & Guesthouses',
      'Hot Spitian Meals Daily',
      'Oxygen and Winter Safety Kits',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Winter Spiti Valley 4x4 White Expedition',
      sourceUrl: 'https://internationalyouthclub.org/tours/winter-spiti-valley',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 35. SPITI: MOTORBIKE CIRCUIT 10D ──
  {
    id: 'spiti-motorbike-circuit-10d',
    destinationId: 'spiti',
    destination: 'Spiti Valley',
    title: 'Spiti Valley High Mountain Motorbike Circuit',
    subtitle: 'Ride through Kinnaur gorge, Kaza, Chandratal and Kunzum pass',
    shortDescription: 'A thrilling 10-day motorcycle ride through the dramatic cliffs of Kinnaur, crossing into Spiti valley and returning across Kunzum Pass.',
    longDescription: 'Ride through Hindustan-Tibet road cliff hangers, explore thousand-year-old Tabo and Key monasteries, and pitch camp under the stars beside Chandratal.',
    durationNights: 9,
    durationDays: 10,
    pricePerPerson: 19900,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 71,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=90&w=2600&auto=format&fit=crop',
      alt: 'Motorcycle on dusty mountain path in Spiti',
      location: 'Kunzum Pass, Spiti',
    },
    route: 'Delhi → Shimla → Kalpa → Kaza → Chandratal → Manali → Delhi',
    inclusions: [
      'Royal Enfield Himalayan with Fuel & Mechanic Support',
      '9 Nights Hotel & Riverside Camps',
      'Breakfast and Dinner Daily',
      'Backup Luggage Vehicle',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Spiti Valley Motorbike Circuit (9N/10D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/spiti-bike-trip',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 36. KASHMIR: GREAT LAKES TREK 8D ──
  {
    id: 'kashmir-great-lakes-trek',
    destinationId: 'kashmir',
    destination: 'Kashmir',
    title: 'Kashmir Great Lakes Alpine Wilderness Trek',
    subtitle: 'Trek across 7 high-altitude turquoise alpine lakes and high mountain passes',
    shortDescription: 'India’s most celebrated alpine lake trek, traversing emerald valleys, wildflower meadows, and seven pristine high mountain lakes.',
    longDescription: 'Trek from Sonamarg to Naranag, crossing high passes over 13,000 ft. Camp beside Vishansar, Kishansar, Gadsar, and Gangabal lakes against the backdrop of Mount Harmukh.',
    durationNights: 7,
    durationDays: 8,
    pricePerPerson: 16500,
    isPriceOnRequest: false,
    rating: 5.0,
    reviewCount: 128,
    category: 'Trekking',
    badge: 'Premier Alpine Trek',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=90&w=2600&auto=format&fit=crop',
      alt: 'Turquoise alpine lake surrounded by green mountain slopes in Kashmir',
      location: 'Vishansar Lake, Kashmir',
    },
    route: 'Srinagar → Sonamarg → Nichnai → Vishansar → Gadsar → Satsar → Gangabal → Naranag',
    inclusions: [
      '7 Nights in High-Altitude Alpine Camps',
      'All Fresh Mountain Meals Prepared by Trek Chef',
      'Certified Wilderness Mountaineering Guide and Porters',
      'Trek Permits and Camping Permissions',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Kashmir Great Lakes Trek (7N/8D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/kashmir-great-lakes',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 37. KASHMIR: TARSAR MARSAR TREK 7D ──
  {
    id: 'kashmir-tarsar-marsar-trek',
    destinationId: 'kashmir',
    destination: 'Kashmir',
    title: 'Tarsar Marsar Twin Alpine Lakes Trek',
    subtitle: 'Walk through pine forests and almond-shaped glacial lakes in Pahalgam valley',
    shortDescription: 'A serene alpine trek starting from Aru valley to the pristine twin glacial lakes of Tarsar and Marsar nestled in velvet meadows.',
    longDescription: 'Hike along the Lidder river from Aru, camp on the shores of crystal-clear Tarsar lake, and watch the water change colors through the day.',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 14500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 84,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Pristine mountain lake nestled under high peaks',
      location: 'Tarsar Lake, Kashmir',
    },
    route: 'Srinagar → Aru → Lidderwat → Shekwas → Tarsar → Sundersar → Marsar → Aru',
    inclusions: [
      '6 Nights Camp Stays with Sleeping Bags & Tents',
      'All Meals During Trek',
      'Experienced Trek Leader & Safety Equipment',
      'Forest Permits and Transport from Srinagar',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Tarsar Marsar Alpine Lake Trek (6N/7D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/tarsar-marsar',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 38. KASHMIR: GUREZ VALLEY 6D (PRICE ON REQUEST) ──
  {
    id: 'kashmir-gurez-valley-border',
    destinationId: 'kashmir',
    destination: 'Kashmir',
    title: 'Gurez Valley & Kishanganga River Border Circuit',
    subtitle: 'Offbeat journey through Razdan pass to Dawar and Habba Khatoon peak',
    shortDescription: 'An untouched valley along the Line of Control, where the jade-green Kishanganga river flows past wooden log hamlets under Habba Khatoon peak.',
    longDescription: 'Cross the 11,600 ft Razdan Pass into the secluded Dard-Shin tribal valley of Gurez. Visit Tulail valley and listen to local poetry by the river.',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 0,
    isPriceOnRequest: true,
    rating: 4.9,
    reviewCount: 42,
    category: 'Offbeat',
    badge: 'Offbeat Border Valley',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1548013146-72479768bada?q=90&w=2600&auto=format&fit=crop',
      alt: 'Pyramid shaped Habba Khatoon mountain peak in Gurez valley',
      location: 'Dawar, Gurez Valley, Kashmir',
    },
    route: 'Srinagar → Razdan Pass → Dawar (Gurez) → Tulail Valley → Srinagar',
    inclusions: [
      '5 Nights in Local Wooden Homestays and Riverside Camps',
      'All Traditional Meals and Chai',
      'Private 4x4 Chauffeur Vehicle from Srinagar',
      'Border Area Permits and Local Guide',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Gurez Valley Offbeat Border Circuit (5N/6D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/gurez-valley-tour',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 39. MEGHALAYA & ASSAM: KAZIRANGA & RAINFORESTS 7D ──
  {
    id: 'meghalaya-kaziranga-wildlife-7d',
    destinationId: 'meghalaya',
    destination: 'Meghalaya',
    title: 'Kaziranga Safari & Meghalaya Rainforest Trails',
    subtitle: 'One-horned rhino jeep safaris combined with Cherrapunji root bridges',
    shortDescription: 'Combine elephant grass safaris in Kaziranga National Park with living root bridges and crystal river canyons in Meghalaya.',
    longDescription: 'Spot the Great Indian One-horned Rhinoceros on open-jeep safaris in Kaziranga, then ascend into the mist-clad hills of Meghalaya to trek double-decker root bridges and boat in Dawki.',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 25500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 65,
    category: 'Wildlife',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=90&w=2600&auto=format&fit=crop',
      alt: 'Misty grasslands and wildlife habitat in Northeast India',
      location: 'Kaziranga National Park, Assam',
    },
    route: 'Guwahati → Kaziranga National Park → Shillong → Cherrapunji → Dawki → Guwahati',
    inclusions: [
      '6 Nights in Jungle Lodges and Eco Cottages',
      'Daily Breakfast and Dinner',
      'Open Jeep Safari in Kaziranga Central / Western Zone',
      'Private Vehicle for All Inter-City Travel and Sightseeing',
      'Park Entry Permits and Guide Fees',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Kaziranga & Meghalaya Wildlife Tour (6N/7D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/kaziranga-meghalaya',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 40. NAGALAND: DZUKOU VALLEY TREK 5D ──
  {
    id: 'nagaland-dzukou-valley-trek',
    destinationId: 'nagaland',
    destination: 'Nagaland',
    title: 'Dzukou Valley Floral Meadow & Hornbill Trail',
    subtitle: 'Trek into the emerald rolling bamboo sanctuary on the Nagaland-Manipur border',
    shortDescription: 'Hike into the surreal green amphitheater of Dzukou Valley, famed for its seasonal lilies, natural rock caves, and panoramic mountain vistas.',
    longDescription: 'Ascend from Viswema village through lush rainforests into the sprawling bamboo valleys of Dzukou. Camp under the stars and experience warm tribal hospitality in Kohima.',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 13500,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 47,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=90&w=2600&auto=format&fit=crop',
      alt: 'Rolling green mountain valley and misty skies in Nagaland',
      location: 'Dzukou Valley, Nagaland',
    },
    route: 'Dimapur → Kohima → Viswema → Dzukou Valley → Jakhama → Dimapur',
    inclusions: [
      '4 Nights in Traditional Homestays and Valley Rest House / Tents',
      'All Meals on Trek and Traditional Naga Dinners',
      'Local Certified Guide and Porters',
      'Inner Line Permits and Entry Fees',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Dzukou Valley & Hornbill Experience (4N/5D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/dzukou-valley',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 41. TAWANG: MOTORBIKE EXPEDITION 11D ──
  {
    id: 'tawang-motorbike-expedition-11d',
    destinationId: 'tawang',
    destination: 'Tawang & Arunachal',
    title: 'Western Arunachal & Tawang Motorbike Expedition',
    subtitle: '11-day motorcycle ride crossing Sela Pass (13,700 ft) and Sangti valley',
    shortDescription: 'A high-adventure motorbike journey across Arunachal Pradesh, riding through cloud forests, snow-clad Sela Pass, and ancient Buddhist monasteries.',
    longDescription: 'Ride through Nameri national park up to Dirang, conquer the misty switchbacks of Sela Pass, and explore the grand 400-year-old Tawang Monastery.',
    durationNights: 10,
    durationDays: 11,
    pricePerPerson: 42499,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 39,
    category: 'Motorbike',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=90&w=2600&auto=format&fit=crop',
      alt: 'Riders climbing high mountain pass with prayer flags',
      location: 'Sela Pass, Arunachal Pradesh',
    },
    route: 'Guwahati → Nameri → Dirang → Sela Pass → Tawang → Sangti Valley → Kaziranga → Guwahati',
    inclusions: [
      'Royal Enfield Himalayan Bike with Fuel',
      '10 Nights in Heritage Lodges and Camps',
      'Breakfast and Dinner Daily',
      'Road Captain, Mechanic & Backup Truck',
      'Inner Line Permits for Arunachal Pradesh',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Tawang Motorbike Expedition (10N/11D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/tawang-bike-trip',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 42. SIKKIM: NORTH SIKKIM GURUDONGMAR 6D ──
  {
    id: 'sikkim-north-gurudongmar-6d',
    destinationId: 'sikkim',
    destination: 'Sikkim & Darjeeling',
    title: 'North Sikkim Gurudongmar & Yumthang Alpine Valley',
    subtitle: 'Sacred Gurudongmar Lake (17,800 ft), Lachen, Lachung & hot springs',
    shortDescription: 'Journey into high alpine North Sikkim to stand beside the sacred turquoise waters of Gurudongmar Lake and explore the rhododendron valley of Yumthang.',
    longDescription: 'Travel from Gangtok along roaring mountain gorges to remote Lachen village. Ascend near the Tibetan plateau to holy Gurudongmar Lake at 17,800 ft, then visit Lachung and Yumthang Valley.',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 18500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 78,
    category: 'Adventure',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Glacial alpine lake surrounded by snow peaks in North Sikkim',
      location: 'Gurudongmar Lake, North Sikkim',
    },
    route: 'Gangtok → Lachen → Gurudongmar Lake (17,800 ft) → Lachung → Yumthang Valley → Gangtok',
    inclusions: [
      '5 Nights in Alpine Guesthouses with Mountain Views',
      'All Meals Included in North Sikkim',
      'Dedicated 4x4 Vehicle with Permit Clearances',
      'Protected Area Permits and Local Guide',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'North Sikkim & Gurudongmar Lake (5N/6D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/north-sikkim-gurudongmar',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 43. UTTARAKHAND: KEDARKANTHA SNOW TREK 6D ──
  {
    id: 'uttarakhand-kedarkantha-snow-trek',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Kedarkantha Winter Snow Summit Trek',
    subtitle: 'Classic winter summit trek to 12,500 ft with 360-degree Himalayan views',
    shortDescription: 'India’s most popular winter summit trek, passing frozen forest ponds at Juda Ka Talab to reach a dramatic 360-degree snow summit.',
    longDescription: 'Trek through deep pine forests from Sankri village, camp on snow clearings beside Juda Ka Talab, and push for the sunrise summit of Kedarkantha (12,500 ft) with views of Swargarohini and Bandarpoonch.',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 7500,
    originalPrice: 9000,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 164,
    category: 'Trekking',
    badge: 'Popular Snow Summit',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Snow summit peak bathed in morning sunlight',
      location: 'Kedarkantha Summit, Uttarakhand',
    },
    route: 'Dehradun → Sankri → Juda Ka Talab → Kedarkantha Base → Summit (12,500 ft) → Sankri → Dehradun',
    inclusions: [
      '5 Nights in Village Guesthouses & Alpine Winter Tents',
      'All Nutritious Vegetarian Trek Meals',
      'Certified Trek Leaders, Microspikes & Gaiters',
      'Forest Permits and Transport from Dehradun',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Kedarkantha Winter Snow Trek (5N/6D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/kedarkantha-trek',
      sourceCheckedAt: '2026-08-21',
      pricingVariantsNote: 'Ex-Dehradun: ₹7,500. Ex-Delhi: ₹9,000.',
    },
  },

  // ── 44. UTTARAKHAND: BRAHMATAL TREK 6D ──
  {
    id: 'uttarakhand-brahmatal-winter-trek',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Brahmatal Alpine Snow Lake Trek',
    subtitle: 'Winter lake trek with panoramic front-row views of Mount Trishul',
    shortDescription: 'A magnificent winter snow trek leading to the frozen glacial lake of Brahmatal with unmatched close-up views of Mount Trishul and Nanda Ghunti.',
    longDescription: 'Trek from Lohajung through rhododendron and oak woods. Camp beside frozen Bekaltal and Brahmatal lakes, and climb to Brahmatal Pass (12,250 ft).',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 6490,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 92,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?q=90&w=2600&auto=format&fit=crop',
      alt: 'Frozen alpine lake surrounded by snow covered mountains',
      location: 'Brahmatal, Uttarakhand',
    },
    route: 'Kathgodam → Lohajung → Bekaltal → Brahmatal → Brahmatal Pass (12,250 ft) → Lohajung',
    inclusions: [
      '5 Nights Camp and Guesthouse Accommodation',
      'All Meals on Trek',
      'Expert Trek Guides and Safety Gear',
      'Forest Entry Fees and Permissions',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Brahmatal Winter Summit & Lake Trek (5N/6D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/brahmatal-trek',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 45. UTTARAKHAND: HAR KI DUN TREK 7D ──
  {
    id: 'uttarakhand-har-ki-dun-trek',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Har Ki Dun Ancient Valley Trail',
    subtitle: 'Trek through ancient wooden villages in the cradle of the Garhwal Himalayas',
    shortDescription: 'A timeless Himalayan valley trek along the Supin river, passing 1,000-year-old carved wooden villages and alpine meadows under Jaundhar glacier.',
    longDescription: 'Walk the legendary path of the Pandavas through the ancient villages of Taluka and Osla. Arrive at the hanging cradle valley of Har Ki Dun with views of Swargarohini peaks.',
    durationNights: 6,
    durationDays: 7,
    pricePerPerson: 8500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 76,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Lush green alpine valley surrounded by mountain peaks',
      location: 'Har Ki Dun Valley, Uttarakhand',
    },
    route: 'Dehradun → Sankri → Taluka → Osla → Har Ki Dun Valley → Sankri → Dehradun',
    inclusions: [
      '6 Nights Homestays & Alpine Camping Stays',
      'All Freshly Cooked Trek Meals',
      'Certified Mountain Leader & Local Village Guides',
      'National Park Permits and Forest Entry',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Har Ki Dun Cradle of Shiva Trek (6N/7D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/har-ki-dun',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 46. UTTARAKHAND: CHARDHAM YATRA 12D (PRICE ON REQUEST) ──
  {
    id: 'uttarakhand-chardham-yatra-delhi-12d',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Complete Sacred Chardham Yatra Circuit',
    subtitle: 'Sacred pilgrimage to Yamunotri, Gangotri, Kedarnath & Badrinath from Delhi',
    shortDescription: 'The revered pilgrimage covering all four sacred Himalayan dhams with comfortable hotel stays, VIP temple assistance, and private transport.',
    longDescription: 'Embark on the revered journey across the Garhwal Himalayas. Visit the holy glacial sources of Yamunotri and Gangotri, hike to the sanctum of Kedarnath, and seek blessings at Badrinath.',
    durationNights: 11,
    durationDays: 12,
    pricePerPerson: 0,
    isPriceOnRequest: true,
    rating: 5.0,
    reviewCount: 145,
    category: 'Spiritual',
    badge: 'Complete 4-Dhams',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=90&w=2600&auto=format&fit=crop',
      alt: 'Ancient Himalayan temple standing against mountain backdrop',
      location: 'Kedarnath & Badrinath, Uttarakhand',
    },
    route: 'Delhi → Haridwar → Barkot → Yamunotri → Uttarkashi → Gangotri → Guptkashi → Kedarnath → Badrinath → Rishikesh → Delhi',
    inclusions: [
      '11 Nights Hotel Accommodation across All Shrines',
      'Breakfast and Dinner Daily',
      'Dedicated Chauffeur AC Vehicle from Delhi',
      'Yatra Registration and Bio-Metric Clearance Assistance',
    ],
    sourceMetadata: {
      source: 'GHUMEGA',
      sourceName: 'Ghumega India',
      sourcePackageName: 'Chardham Yatra from Delhi (11N/12D)',
      sourceUrl: 'https://www.ghumegaindia.com/chardham-tours/chardham-yatra-delhi',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 47. UTTARAKHAND: DO DHAM YATRA 5D (PRICE ON REQUEST) ──
  {
    id: 'uttarakhand-do-dham-kedarnath-badrinath',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Do Dham Yatra (Kedarnath & Badrinath)',
    subtitle: 'Focused sacred pilgrimage to Kedarnath and Badrinath shrines',
    shortDescription: 'A streamlined 5-day spiritual circuit to the two most revered Himalayan sanctums: Kedarnath and Badrinath.',
    longDescription: 'Travel from Haridwar through the scenic Mandakini and Alaknanda valleys. Stand before the ancient stone lingam of Kedarnath and visit Badrinath temple.',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 0,
    isPriceOnRequest: true,
    rating: 4.9,
    reviewCount: 96,
    category: 'Spiritual',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Kedarnath valley mountain vista',
      location: 'Kedarnath, Uttarakhand',
    },
    route: 'Haridwar → Guptkashi → Kedarnath → Joshimath → Badrinath → Haridwar',
    inclusions: [
      '4 Nights Hotel & Guesthouse Stays',
      'Daily Vegetarian Meals',
      'Dedicated Chauffeur Car for All Valley Transfers',
      'Priority Darshan Assistance',
    ],
    sourceMetadata: {
      source: 'GHUMEGA',
      sourceName: 'Ghumega India',
      sourcePackageName: 'Do Dham Yatra (Kedarnath & Badrinath 4N/5D)',
      sourceUrl: 'https://www.ghumegaindia.com/chardham-tours/do-dham-kedarnath-badrinath',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 48. UTTARAKHAND: CORBETT WILDLIFE 3D (PRICE ON REQUEST) ──
  {
    id: 'uttarakhand-corbett-wildlife-weekend',
    destinationId: 'uttarakhand',
    destination: 'Uttarakhand',
    title: 'Jim Corbett Tiger Safari Weekend Escape',
    subtitle: 'Open jeep tiger safaris and riverside jungle resort in Ramnagar',
    shortDescription: 'A quick weekend wildlife retreat to India’s oldest national park, exploring Sal forests on open jeep safaris with naturalist guides.',
    longDescription: 'Unwind at a riverside jungle resort by the Kosi river. Venture into Bijrani or Jhirna safari zones in search of Bengal tigers, wild Asian elephants, and diverse birdlife.',
    durationNights: 2,
    durationDays: 3,
    pricePerPerson: 0,
    isPriceOnRequest: true,
    rating: 4.8,
    reviewCount: 52,
    category: 'Wildlife',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=90&w=2600&auto=format&fit=crop',
      alt: 'Dense sal forest and river bed in Corbett national park',
      location: 'Jim Corbett National Park, Uttarakhand',
    },
    route: 'Delhi → Jim Corbett National Park → Ramnagar → Delhi',
    inclusions: [
      '2 Nights in Riverside Jungle Resort with Pool',
      'All Buffet Meals (Breakfast, Lunch, Dinner)',
      '1 Exclusive Open-Top Gypsy Jeep Safari with Naturalist',
      'Permits and Forest Entry Fees',
    ],
    sourceMetadata: {
      source: 'GHUMEGA',
      sourceName: 'Ghumega India',
      sourcePackageName: '2 Nights / 3 Days Corbett Wildlife Tour',
      sourceUrl: 'https://www.ghumegaindia.com/uttarakhand-tours/corbett-weekend',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 49. HIMACHAL: HAMPTA PASS TREK 5D ──
  {
    id: 'himachal-hampta-pass-trek',
    destinationId: 'himachal',
    destination: 'Himachal Pradesh',
    title: 'Hampta Pass & Chandratal Crossover Alpine Trek',
    subtitle: 'Dramatic crossover from Kullu green pine valleys to barren Spiti',
    shortDescription: 'A classic crossover trek climbing from the lush green pine glades of Manali over Hampta Pass (14,065 ft) into the desert mountains of Spiti.',
    longDescription: 'Walk from Jobra through wildflower meadows at Balu Ka Ghera, cross the icy Hampta Pass ridge, descend into the lunar landscape of Shea Goru, and drive to crescent-shaped Chandratal.',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 4800,
    originalPrice: 8500,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 134,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'High mountain crossover pass in Himachal Pradesh',
      location: 'Hampta Pass, Himachal Pradesh',
    },
    route: 'Manali → Jobra → Chika → Balu Ka Ghera → Hampta Pass (14,065 ft) → Shea Goru → Chatru → Chandratal → Manali',
    inclusions: [
      '4 Nights Alpine Camping with Sleeping Bags',
      'Nutritious High-Altitude Meals',
      'Certified Mountain Guide & Safety Equipment',
      'Transfer to Chandratal Lake and back to Manali',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Hampta Pass & Chandratal Crossover Trek (4N/5D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/hampta-pass',
      sourceCheckedAt: '2026-08-21',
      pricingVariantsNote: 'Ex-Manali base rate: ₹4,800. Ex-Delhi with Volvo: ₹8,500.',
    },
  },

  // ── 50. HIMACHAL: SAR PASS TREK 6D ──
  {
    id: 'himachal-sar-pass-trek',
    destinationId: 'himachal',
    destination: 'Himachal Pradesh',
    title: 'Sar Pass Snow Slide & Alpine Meadow Trek',
    subtitle: 'Parvati valley pine forests, high snow camp at Nagaru & thrilling snow slides',
    shortDescription: 'A quintessential summer Himalayan trek from Kasol passing Grahan village, ascending to snow-capped Sar Pass (13,800 ft), and descending through Biskeri Thach.',
    longDescription: 'Hike through fairy-tale pine woods and traditional wooden villages in Parvati Valley. Reach the high snow camp at Nagaru and experience the exhilarating natural snow slide after crossing Sar Pass.',
    durationNights: 5,
    durationDays: 6,
    pricePerPerson: 9900,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 118,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=90&w=2600&auto=format&fit=crop',
      alt: 'Snow ridge and trekkers crossing mountain pass',
      location: 'Sar Pass, Himachal Pradesh',
    },
    route: 'Delhi → Kasol → Grahan → Min Thach → Nagaru → Sar Pass (13,800 ft) → Biskeri Thach → Barshaini → Delhi',
    inclusions: [
      '5 Nights in Kasol Camps and High-Altitude Tents',
      'All Freshly Prepared Trek Meals',
      'Certified Trek Leaders and Porters',
      'Roundtrip Semi-Sleeper Volvo Transport from Delhi',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Sar Pass Trek Ex-Delhi (5N/6D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/sar-pass',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 51. HIMACHAL: BEAS KUND TREK 3D ──
  {
    id: 'himachal-beas-kund-trek',
    destinationId: 'himachal',
    destination: 'Himachal Pradesh',
    title: 'Beas Kund Glacial Source Trek',
    subtitle: 'Short 3-day weekend trek from Manali to the origin of the Beas River',
    shortDescription: 'A classic beginner-friendly weekend trek passing through Solang valley and Bakarthach meadows to the glacial lake of Beas Kund.',
    longDescription: 'Climb along the Beas river through towering birch woods to Bakarthach. Reach the glacial emerald waters of Beas Kund (12,772 ft) nestled beneath Hanuman Tibba and Friendship Peak.',
    durationNights: 2,
    durationDays: 3,
    pricePerPerson: 3900,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 68,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=90&w=2600&auto=format&fit=crop',
      alt: 'Alpine glacial pond reflecting snow peaks',
      location: 'Beas Kund, Manali',
    },
    route: 'Manali → Solang Nallah → Dhundi → Bakarthach → Beas Kund (12,772 ft) → Manali',
    inclusions: [
      '2 Nights Alpine Camp Stay with Sleeping Bags',
      'All Meals on Trek',
      'Experienced Mountaineering Guide',
      'Trek Permits and First Aid Kit',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Beas Kund High Altitude Glacial Lake Trek (2N/3D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/beas-kund',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 52. HIMACHAL: BHRIGU LAKE TREK 3D ──
  {
    id: 'himachal-bhrigu-lake-trek',
    destinationId: 'himachal',
    destination: 'Himachal Pradesh',
    title: 'Bhrigu Lake High Alpine Ridge Trek',
    subtitle: 'Ascend to 14,100 ft alpine lake through velvet green meadows from Manali',
    shortDescription: 'A picturesque high-altitude meadow trek starting from Gulaba, reaching the sacred alpine waters of Bhrigu Lake.',
    longDescription: 'Trek through sprawling grasslands with expansive views of the Pir Panjal range. Camp at Rola Kholi and hike to holy Bhrigu Lake at 14,100 ft.',
    durationNights: 2,
    durationDays: 3,
    pricePerPerson: 3900,
    isPriceOnRequest: false,
    rating: 4.8,
    reviewCount: 54,
    category: 'Trekking',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=90&w=2600&auto=format&fit=crop',
      alt: 'Rolling high-altitude green meadows and alpine ridge',
      location: 'Bhrigu Lake, Manali',
    },
    route: 'Manali → Gulaba → Rola Kholi → Bhrigu Lake (14,100 ft) → Pandu Ropa → Vashisht',
    inclusions: [
      '2 Nights High Meadow Camp Stays',
      'All Vegetarian Mountain Meals',
      'Certified Trek Leader & First Aid',
      'Transport from Manali to Gulaba & return',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Bhrigu Lake Alpine Meadow Trek (2N/3D)',
      sourceUrl: 'https://internationalyouthclub.org/treks/bhrigu-lake',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 53. HIMACHAL: BIR BILLING PARAGLIDING 3D ──
  {
    id: 'himachal-bir-billing-paragliding',
    destinationId: 'himachal',
    destination: 'Himachal Pradesh',
    title: 'Bir Billing Paragliding Flight & Pine Valley Camping',
    subtitle: 'Tandem paragliding flight from 8,000 ft, Tibetan monasteries & sunset camps',
    shortDescription: 'Fly like a bird over the Kangra valley from Billing takeoff (8,000 ft), explore tranquil Tibetan monasteries, and camp under star-lit skies in Bir.',
    longDescription: 'Visit the world’s second-highest paragliding site. Experience a 20-minute tandem flight with certified pilots, visit Chokling Monastery, and café hop in Bir village.',
    durationNights: 2,
    durationDays: 3,
    pricePerPerson: 5250,
    isPriceOnRequest: false,
    rating: 4.9,
    reviewCount: 98,
    category: 'Adventure',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=90&w=2600&auto=format&fit=crop',
      alt: 'Paraglider soaring high in the blue sky over mountain valley',
      location: 'Billing Takeoff, Himachal Pradesh',
    },
    route: 'Delhi → Bir → Billing Takeoff (8,000 ft) → Tibetan Colony → Delhi',
    inclusions: [
      '2 Nights Boutique Camp Stay in Bir with Bonfire',
      'Tandem Paragliding Flight with GoPro Video Footage',
      'Daily Breakfast and Dinner',
      'Monastery and Local Village Guided Walk',
    ],
    sourceMetadata: {
      source: 'IYC',
      sourceName: 'International Youth Club',
      sourcePackageName: 'Bir Billing Paragliding & Camping (2N/3D)',
      sourceUrl: 'https://internationalyouthclub.org/tours/bir-billing-paragliding',
      sourceCheckedAt: '2026-08-21',
    },
  },

  // ── 54. RAJASTHAN & NORTH INDIA: GOLDEN TRIANGLE 5D (PRICE ON REQUEST) ──
  {
    id: 'rajasthan-golden-triangle-classic',
    destinationId: 'rajasthan',
    destination: 'Rajasthan',
    title: 'Golden Triangle Heritage Circuit (Delhi, Agra & Jaipur)',
    subtitle: 'Taj Mahal at sunrise, Mughal fortresses & royal pink city palaces',
    shortDescription: 'The quintessential cultural circuit of India, exploring Mughal architecture in Delhi and Agra, and royal Rajput palaces in Jaipur.',
    longDescription: 'Marvel at the white marble symmetry of the Taj Mahal at dawn, walk the red sandstone ramparts of Agra Fort and Fatehpur Sikri, and tour the Amber Fort and City Palace in Jaipur.',
    durationNights: 4,
    durationDays: 5,
    pricePerPerson: 0,
    isPriceOnRequest: true,
    rating: 4.9,
    reviewCount: 110,
    category: 'Heritage',
    coverImage: {
      src: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?q=90&w=2600&auto=format&fit=crop',
      alt: 'Sunlit royal fortress courtyard in Rajasthan',
      location: 'Amber Fort, Jaipur',
    },
    route: 'Delhi → Agra (Taj Mahal) → Fatehpur Sikri → Jaipur → Delhi',
    inclusions: [
      '4 Nights in 4-Star Heritage & Boutique Hotels',
      'Daily Buffet Breakfast',
      'Private AC Chauffeur Sedan for Entire Circuit',
      'Local Certified Historian Guides in Agra and Jaipur',
    ],
    sourceMetadata: {
      source: 'GHUMEGA',
      sourceName: 'Ghumega India',
      sourcePackageName: 'Golden Triangle Classic Tour (Delhi-Agra-Jaipur 4N/5D)',
      sourceUrl: 'https://www.ghumegaindia.com/golden-triangle/classic-golden-triangle',
      sourceCheckedAt: '2026-08-21',
    },
  },
];

const all54Packages: TripPackage[] = [...existing26, ...confirmed28];

console.log(`Total packages to write: ${all54Packages.length}`);
console.log(`Existing count: ${existing26.length}`);
console.log(`New confirmed imports count: ${confirmed28.length}`);

// Write back formatted TypeScript file
const fileHeader = `import { TripPackage } from '@/types';\n\nexport const tripPackages: TripPackage[] = `;
const fileContent = `${fileHeader}${JSON.stringify(all54Packages, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, '../src/data/trips.ts'), fileContent, 'utf-8');
console.log('Successfully updated src/data/trips.ts with all 54 packages!');
